import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full bg-gradient-to-br from-blue-50 via-white to-pink-100 font-sans">
      <body className="min-h-screen flex flex-col items-center justify-center text-gray-800 antialiased selection:bg-blue-200 selection:text-blue-900">
        <main className="w-full max-w-3xl p-4 sm:p-8 rounded-2xl shadow-xl bg-white/80 backdrop-blur-md mt-8 mb-8">
          {children}
        </main>
      </body>
    </html>
  )
}
